[package]
name = "eye-spy"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
multiqueue = "0.3.2"
openh264 = {version = "0.6.2", features=["libloading", "source"]} 
sdl2 = "0.37.0"
v4l = "0.14.0"
